### ISSUE TITLE
reflection config suggestion doesn't work

### ISSUE THREAD

**Issue by andreivolt** [borkdude/clj-reflector-graal-java11-fix#5]
Just a heads-up, I tried to build https://github.com/hagmonk/find-deps with the suggested reflection config and it failed, I had to add entries with `"allPublicMethods": true" for each class. Apparently there's no way to specify a wildcard, though I would appreciate hints on how to gather all those class names automatically, perhaps with some static analysis?

**Comment by borkdude** [comment]
@andreivolt What do you mean "for each class"?

**Comment by andreivolt** [comment]
In this case it was reflection for some java.io classes, but I was just coming back to this issue to tell you I stumbled upon https://github.com/borkdude/tools-deps-native-experiment/blob/master/script/gen-reflect-config.clj which looks like exactly what I need.

**Comment by borkdude** [comment]
You can find more information about that here: https://github.com/borkdude/refl

But it's usually better to get rid of the reflection warnings if you can in the Clojure code itself.

**Comment by andreivolt** [comment]
Thank you I will!
